packages:
  - "packages/app"
  - "packages/vitest"
  - "packages/__tests__/project1"
  - "packages/solidjs"
  - "packages/reactjs"
  - "packages/utils/bemedev"
  - "packages/utils/vitest"
  - "packages/cli"

allowBuilds:
  esbuild: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/*'
