packages:
  - "packages/app"
  - "packages/vitest"
  - "packages/__tests__/project1"
  - "packages/solidjs"
  - "packages/solidjs-vitest"
  - "packages/utils/bemedev"
  - "packages/utils/vitest"

allowBuilds:
  esbuild: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/dev-utils@0.8.0'
