/**
 * This file is auto-generated by the @bemedev/app CLI.
 * Do not edit manually. Re-run `app generate` or restart `app watch`.
 *
 */

declare module '@bemedev/app' {
  interface Register {
    'src/__tests__/actions/action.batch.cov.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'INC1' | 'INC2' | 'INC5';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'inc1' | 'inc2' | 'inc5';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/actions.1.machine': {
      paths: {
        map: { targets: ('/state1' | '/state2'); 
        initial: 'state1';
        states: {
          'state1': { targets: ('/' | '/state2'); 
          };
          'state2': { targets: ('/' | '/state1'); 
          };
        };
      };
        all: '/' | '/state1' | '/state2';
      };
      events: 'NEXT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'action1';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/actions.2.machine': {
      paths: {
        map: { targets: ('/state1' | '/state2'); 
        initial: 'state1';
        states: {
          'state1': { targets: ('/' | '/state2'); 
          };
          'state2': { targets: ('/' | '/state1'); 
          };
        };
      };
        all: '/' | '/state1' | '/state2';
      };
      events: 'NEXT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'action1';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.1.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'loadUser';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.2.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'loadUser';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.3.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'loadUser';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.4.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'PING';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'ping';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.5.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'PING';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'ping';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.6.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'FILTER';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'filterEven';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.7.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'DISPATCH';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'dispatchEvent';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.8.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'INC';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'inc';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/sendToActions/sendToActions1.machine': {
      paths: {
        map: { targets: ('/idle' | '/next'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/' | '/next'); 
          };
          'next': { targets: ('/' | '/idle'); 
          };
        };
      };
        all: '/' | '/idle' | '/next';
      };
      events: 'DECREMENT' | 'INCREMENT' | 'REDECREMENT' | 'NEXT' | 'INCREMENT.FORCE';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'init' | 'dec' | 'inc' | 'sendDec' | 'forceSendInc';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/actions/sendToActions/sendToActions2.machine': {
      paths: {
        map: { targets: ('/idle' | '/next'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/' | '/next'); 
          };
          'next': { targets: ('/' | '/idle'); 
          };
        };
      };
        all: '/' | '/idle' | '/next';
      };
      events: 'DECREMENT' | 'INCREMENT' | 'REDECREMENT' | 'NEXT' | 'INCREMENT.FORCE';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'init' | 'dec' | 'inc' | 'sendDec' | 'forceSendInc';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/delays/delay.notDefined.machine': {
      paths: {
        map: { targets: ('/idle' | '/active'); 
        initial: 'idle';
        states: {
          'active': { targets: ('/' | '/idle'); 
          };
          'idle': { targets: ('/' | '/active'); 
          };
        };
      };
        all: '/' | '/idle' | '/active';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   'DELAY';
        guards:   never;
      };
      pContext: any;
    };

    'arrayAsyncAssign': {
      paths: {
        map: { targets: (never); 
      };
        all: '/';
      };
      events: 'INC';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'incthearray';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'arrayAssign': {
      paths: {
        map: { targets: (never); 
      };
        all: '/';
      };
      events: 'INC';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'incthearray';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'edges.arrayAssign.complex': {
      paths: {
        map: { targets: (never); 
      };
        all: '/';
      };
      events: 'INC';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'incDeep';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'edges.arrayAssign.sync.complex': {
      paths: {
        map: { targets: (never); 
      };
        all: '/';
      };
      events: 'INC';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'incDeep';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'arrayAssignSync': {
      paths: {
        map: { targets: (never); 
      };
        all: '/';
      };
      events: 'INC';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'incthearray';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'atomic': {
      paths: {
        map: { targets: (never); 
      };
        all: '/';
      };
      events: 'SET_LANG';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'setLang';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/guards/index.1.machine': {
      paths: {
        map: { targets: ('/state1' | '/state2'); 
        initial: 'state1';
        states: {
          'state1': { targets: ('/' | '/state2'); 
          };
          'state2': { targets: ('/' | '/state1'); 
          };
        };
      };
        all: '/' | '/state1' | '/state2';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   'guard1';
      };
      pContext: any;
    };

    'src/__tests__/guards/index.2.machine': {
      paths: {
        map: { targets: ('/state1' | '/state2'); 
        initial: 'state1';
        states: {
          'state1': { targets: ('/' | '/state2'); 
          };
          'state2': { targets: ('/' | '/state1'); 
          };
        };
      };
        all: '/' | '/state1' | '/state2';
      };
      events: 'NEXT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   'guard1';
      };
      pContext: any;
    };

    'src/__tests__/guards/index.3.machine': {
      paths: {
        map: { targets: ('/state1' | '/state2'); 
        initial: 'state1';
        states: {
          'state1': { targets: ('/' | '/state2'); 
          };
          'state2': { targets: ('/' | '/state1'); 
          };
        };
      };
        all: '/' | '/state1' | '/state2';
      };
      events: 'NEXT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   'guard1';
      };
      pContext: any;
    };

    'src/__tests__/guards/index.4.machine': {
      paths: {
        map: { targets: ('/state1' | '/state2'); 
        initial: 'state1';
        states: {
          'state1': { targets: ('/' | '/state2'); 
          };
          'state2': { targets: ('/' | '/state1'); 
          };
        };
      };
        all: '/' | '/state1' | '/state2';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   'returnTrue' | 'returnFalse' | 'returnTrue2' | 'returnFalse2';
      };
      pContext: { data: string };
    };

    'src/__tests__/machine/addOptions-return.1.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'INCREMENT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'increment';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/addOptions-return.2.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/addOptions-return.3.machine': {
      paths: {
        map: { targets: ('/idle' | '/positive'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/' | '/positive'); 
          };
          'positive': { targets: ('/' | '/idle'); 
          };
        };
      };
        all: '/' | '/idle' | '/positive';
      };
      events: 'CHECK';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   'isPositive';
      };
      pContext: any;
    };

    'src/__tests__/machine/addOptions-return.4.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'INCREMENT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'increment';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/cov.1.machine': {
      paths: {
        map: { targets: ('/idle' | '/state1' | '/state1/state11' | '/state1/state11/state111' | '/state1/state11/state111/state1111' | '/state1/state11/state112'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/' | '/state1' | '/state1/state11' | '/state1/state11/state111' | '/state1/state11/state111/state1111' | '/state1/state11/state112'); 
          };
          'state1': { targets: ('/' | '/idle' | '/state1/state11' | '/state1/state11/state111' | '/state1/state11/state111/state1111' | '/state1/state11/state112'); 
            initial: 'state11';
            states: {
              'state11': { targets: ('/' | '/idle' | '/state1' | '/state1/state11/state111' | '/state1/state11/state111/state1111' | '/state1/state11/state112'); 
                initial: 'state111';
                states: {
                  'state111': { targets: ('/' | '/idle' | '/state1' | '/state1/state11' | '/state1/state11/state111/state1111' | '/state1/state11/state112'); 
                    initial: 'state1111';
                    states: {
                      'state1111': { targets: ('/' | '/idle' | '/state1' | '/state1/state11' | '/state1/state11/state111' | '/state1/state11/state112'); 
                      };
                    };
                  };
                  'state112': { targets: ('/' | '/idle' | '/state1' | '/state1/state11' | '/state1/state11/state111' | '/state1/state11/state111/state1111'); 
                  };
                };
              };
            };
          };
        };
      };
        all: '/' | '/idle' | '/state1' | '/state1/state11' | '/state1/state11/state111' | '/state1/state11/state111/state1111' | '/state1/state11/state112';
      };
      events: 'NEXT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'inc';
        delays:   'DELAY';
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/cov.2.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: '[idM]';
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/cov.3.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: '[idM.name]';
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/longRuns.cov.1.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/longRuns.cov.2.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/longRuns.cov.3.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'TEST';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'slowAction';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/longRuns.cov.4.machine': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: 'TEST';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'slowAction';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

    'src/__tests__/machine/longRuns.cov.5.machine': {
      paths: {
        map: { targets: ('/idle' | '/active'); 
        initial: 'idle';
        states: {
          'active': { targets: ('/' | '/idle'); 
          };
          'idle': { targets: ('/' | '/active'); 
          };
        };
      };
        all: '/' | '/idle' | '/active';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   'DELAY';
        guards:   never;
      };
      pContext: any;
    };

  }
}

export {};