import { parseTree } from '#utils';
import { existsSync, unlinkSync } from 'fs';
import { writeFile } from 'fs/promises';
import fg from 'fast-glob';
import { relative, resolve } from 'node:path';
import { Project } from 'ts-morph';
import {
  DEFAULT_EXCLUDES,
  DEFAULT_OUTPUT,
  MACHINE_GLOB,
} from './constants';
import { emitRegisterEntry, extractMachineInfo } from './helpers';

// ── Helpers delegated to src/core/helpers ─────────────────────────────────

// ── Public API ────────────────────────────────────────────────────────

/**
 * 
 * @param options - Configuration object
 * @param output [options.output='app.gen.ts'] - Output file path (relative to cwd)
 * @param excludes [options.excludes] - Glob patterns to exclude (e.g., ['node_modules', 'dist'])
 * @param cwd [options.cwd] - Working directory (defaults to process.cwd())
 * @param dryRun [options.dryRun=false] - If true, output to stdout instead of writing file
 *
 * Generate app.gen.ts from all *.machine.ts / *.fsm.ts files in the workspace.
 *
 * Main entry point for CLI commands. Orchestrates the entire 4-phase generation pipeline:
 * 1. **Discovery**: Find all machine files matching the glob pattern
 * 2. **Extraction**: Use ts-morph to parse and extract config + typings from each file
 * 3. **Analysis**: Delegate to parseTree for symbol set extraction
 * 4. **Emission**: Generate TypeScript type definitions inlined into app.gen.ts
 *
 * The resulting file is a single module declaration augmenting '@bemedev/app':
 * ```typescript
 * declare module '@bemedev/app' {
 *   interface Register {
 *     'machine-name': { paths: {...}, events, options, pContext?, tags? }
 *     // ... one entry per machine, sorted alphabetically
 *   }
 * }
 * export {};
 * ```
 *
 * Key features:
 * - **Hermetic**: No runtime imports or side effects
 * - **Deterministic**: Entries sorted alphabetically for stable diffs
 * - **Type-safe**: All string options become exact literal unions
 * - **Timestamped**: Output marked with generation time for tracking
 *

 *
 * @example
 * // One-time generation
 * await generator({ output: 'app.gen.ts', cwd: process.cwd() });
 *
 * @example
 * // Dry-run for inspection
 * await generator({ dryRun: true });
 *
 * @example
 * // With custom excludes
 * await generator({
 *   excludes: ['node_modules', 'dist', 'temp'],
 *   cwd: '/path/to/project'
 * });
 */
export const generator = async (
  options: {
    excludes?: string[];
    cwd?: string;
    dryRun?: boolean;
  } = {},
) => {
  const EXCLUDES = [...(options.excludes || [])]
    .filter(Boolean)
    .map(pattern => pattern.trim());

  const cwd = options.cwd ?? process.cwd();
  const outputPath = resolve(cwd, DEFAULT_OUTPUT);

  // Discover machine files
  const files = await fg.async(MACHINE_GLOB, {
    cwd,
    ignore: [...EXCLUDES, ...DEFAULT_EXCLUDES],
    dot: true,
    absolute: true,
  });

  if (files.length === 0) {
    if (existsSync(outputPath)) {
      unlinkSync(outputPath);
      console.log(
        `[app] Removed ${relative(cwd, outputPath)} because no machine files were found.`,
      );
    } else {
      console.log('[app] No machine files found.');
    }
    return;
  }

  /** Create a single ts-morph Project for all files */
  const project = new Project({
    tsConfigFilePath: resolve(process.cwd(), 'tsconfig.json'),
    skipAddingFilesFromTsConfig: true,
  });

  for (const f of files) {
    project.addSourceFileAtPath(f);
  }

  const entries: string[] = [];

  // #region TS morph work
  /* v8 ignore start -- @preserve */
  for (const f of files.sort()) {
    const info = extractMachineInfo(f, project);
    if (!info) {
      console.warn(`[app] Skipping: ${relative(cwd, f)}`);
      continue;
    }

    const tree = parseTree(info.config);
    entries.push(emitRegisterEntry(info.name, tree, info.pContextType));
  }

  if (entries.length === 0) {
    if (existsSync(outputPath)) {
      unlinkSync(outputPath);
      console.log(
        `[app] Removed ${relative(cwd, outputPath)} because no valid machine entries were generated.`,
      );
    } else {
      console.log('[app] No valid machine entries were found.');
    }
    return;
  }
  /* v8 ignore stop -- @preserve */
  // #endregion

  /** Emit the generated file */
  const contentArray = [
    `/**`,
    ` * This file is auto-generated by the @bemedev/app CLI.`,
    ` * Do not edit manually. Re-run \`app generate\` or restart \`app watch\`.`,
    ` *`,
    ` */`,
    ``,
    `declare module '@bemedev/app' {`,
    `  interface Register {`,
    entries.join('\n\n'),
    ``,
    `  }`,
    `}`,
    ``,
  ];
  const content = contentArray.join('\n');

  /* v8 ignore else -- @preserve */
  if (options.dryRun) {
    process.stdout.write(content);
    return contentArray;
  }

  /* v8 ignore start -- @preserve */
  return writeFile(outputPath, content, 'utf-8').then(() => {
    console.log(
      `[app] Written: ${relative(cwd, outputPath)} (${entries.length} machines)`,
    );
  });
  /* v8 ignore stop -- @preserve */
};
