/**
 * This file is auto-generated by the @bemedev/app CLI.
 * Do not edit manually. Re-run `app generate` or restart `app watch`.
 *
 */

declare module '@bemedev/app' {
  interface Register {
    'machine': {
      paths: {
        map: { targets: ('/idle' | '/working'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/' | '/working'); 
          };
          'working': { targets: ('/' | '/idle'); 
          };
        };
      };
        all: '/' | '/idle' | '/working';
      };
      events: 'START' | 'CONNECT';
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  'connectEdge';
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };

  }
}

export {};