import {} from '@bemedev/dev-utils/utils';
import { sleep } from '@bemedev/sleep';
import { run } from 'cmd-ts';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmdirSync,
  unlinkSync,
  writeFileSync,
} from 'fs';
import type { Watcher } from 'node-watch';
import { dirname, resolve } from 'path';
import { generate } from './commands/generate';
import { watch } from './commands/watch';
import { LIB } from './core/constants';
import { produceStarterContent } from './core/helpers';
const IS_EXTENSION = process.env.VITEST_VSCODE === 'true';

describe('CLI', () => {
  // #region Config

  // #region FILE CONTENTS
  const OUPUT =
    "/**\n * This file is auto-generated by the @bemedev/app CLI.\n * Do not edit manually. Re-run `app generate` or restart `app watch`.\n *\n */\n\ndeclare module '@bemedev/app' {\n  interface Register {\n    'actions': {\n      paths: {\n        map: { targets: ('/idle'); \n        initial: 'idle';\n        states: {\n          'idle': { targets: ('/'); \n          };\n        };\n      };\n        all: '/' | '/idle';\n      };\n      events: never;\n      options: {\n        children: never;\n        emitters: never;\n        tags:     never;\n        actions:  never;\n        delays:   never;\n        guards:   never;\n      };\n      pContext: any;\n    };\n\n    'watch': {\n      paths: {\n        map: { targets: ('/idle'); \n        initial: 'idle';\n        states: {\n          'idle': { targets: ('/'); \n          };\n        };\n      };\n        all: '/' | '/idle';\n      };\n      events: never;\n      options: {\n        children: never;\n        emitters: never;\n        tags:     never;\n        actions:  never;\n        delays:   never;\n        guards:   never;\n      };\n      pContext: any;\n    };\n\n  }\n}\n\nexport {};".trim();

  const OUPUT1 = [
    '/**',
    ' * This file is auto-generated by the @bemedev/app CLI.',
    ' * Do not edit manually. Re-run `app generate` or restart `app watch`.',
    ' *',
    ' */',
    '',
    "declare module '@bemedev/app' {",
    '  interface Register {',
    `    'actions': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };`,
    '',
    '  }',
    '}',
    '',
    `export {};`,
  ];

  const ACTION_FSM_CONTENT = `import { createMachine } from '${LIB}';
import { typings } from '#utils/typings';

export default createMachine(
  'actions',
  {
    initial: 'idle',
    states: { idle: {} },
  },
  {
    pContext: typings.pContext({
      count: 'number',
    }),
  },
);
`;
  // #endregion

  let watcher: Watcher;
  const CREATED_FILE = './src/__tests__/watch.machine.ts';
  const DIR = dirname(CREATED_FILE);
  const fsmPath = `${DIR}/actions.fsm.ts`;
  const spy = vi.spyOn(process, 'cwd');
  const WAITER = 500;

  beforeAll(() => {
    if (IS_EXTENSION) {
      spy.mockReturnValue(resolve(process.cwd(), 'packages/cli'));
    }
  });

  afterAll(() => spy.mockRestore());

  test('#-01 => Create strcuture folder', async () => {
    mkdirSync(resolve(process.cwd(), DIR), { recursive: true });
    writeFileSync(resolve(process.cwd(), fsmPath), ACTION_FSM_CONTENT);
    await sleep(WAITER);
  });
  // #endregion

  it('#00 => create watcher', async ({ onTestFinished }) => {
    watcher = await run(watch, ['-c', resolve(process.cwd(), DIR)]);
    onTestFinished(() => console.warn('watcher started'));
  });

  it('#01 => create file', async ({ onTestFinished }) => {
    await sleep(WAITER).then(() => {
      writeFileSync(resolve(process.cwd(), CREATED_FILE), '', {
        mode: '777',
      });
    });
    onTestFinished(() => console.warn('writing ....'));
  });

  it('#02 => close watcher', async ({ onTestFinished }) => {
    await sleep(WAITER).then(() => watcher.close());
    onTestFinished(() => console.warn('watcher closed'));
  });

  it('#03 => check file content', async ({ onTestFinished }) => {
    const received = readFileSync(
      resolve(process.cwd(), CREATED_FILE),
      'utf-8',
    );
    expect(received).toBe(produceStarterContent(CREATED_FILE));
    onTestFinished(() => console.warn('file content checked'));
  });

  it('#04 => delete file', async ({ onTestFinished }) => {
    await sleep(WAITER / 5).then(() =>
      unlinkSync(resolve(process.cwd(), CREATED_FILE)),
    );
    onTestFinished(() => console.warn('file deleted'));
  });

  it('#05 => check generated file', async ({ onTestFinished }) => {
    const generated = readFileSync(
      resolve(process.cwd(), `${DIR}/app.gen.ts`),
      'utf-8',
    ).trim();

    expect(generated).toBe(OUPUT);
    onTestFinished(() => console.warn('generated file checked'));
  });

  it('#06 => cli generate', async ({ onTestFinished }) => {
    const result = await run(generate, ['-c', DIR, '--dry-run']);
    expect(result).toEqual(OUPUT1);
    onTestFinished(() => console.warn('generated file for dry-run'));
  });

  it('#07 => delete the only machine left', async ({ onTestFinished }) => {
    await sleep(WAITER / 5).then(() => {
      const exists = existsSync(
        resolve(process.cwd(), `${DIR}/app.gen.ts`),
      );
      expect(exists).toBe(true);
      unlinkSync(resolve(process.cwd(), `${DIR}/actions.fsm.ts`));
    });

    onTestFinished(() => console.warn('All machine files are deleted'));
  });

  it('#08 => cli generate', () => {
    return run(generate, ['-c', DIR, '--dry-run']);
  });

  it('#09 => check generated file is removed', ({ onTestFinished }) => {
    const exists = existsSync(resolve(process.cwd(), `${DIR}/app.gen.ts`));
    expect(exists).toBe(false);
    onTestFinished(() => console.warn('generated file is removed'));
  });

  it('#10 => cli generate', () => {
    return run(generate, ['-c', DIR, '--dry-run']);
  });

  it('#11 => No files inside __tests__', () => {
    const files = readdirSync(resolve(process.cwd(), DIR));
    expect(files.length).toBe(0);
  });

  it('#12 => unlink the dir', ({ onTestFinished }) => {
    rmdirSync(resolve(process.cwd(), DIR));
    onTestFinished(() => console.warn('__tests__ dir is deleted', '\n\n'));
  });
});
