import { sleep } from '@bemedev/sleep';
import { run } from 'cmd-ts';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmdirSync,
  unlinkSync,
  writeFileSync,
} from 'fs';
import type { Watcher } from 'node-watch';
import { dirname } from 'path';
import { generate } from './commands/generate';
import { watch } from './commands/watch';
import { LIB } from './core/constants';

const OUPUT =
  "/**\n * This file is auto-generated by the @bemedev/app CLI.\n * Do not edit manually. Re-run `app generate` or restart `app watch`.\n *\n */\n\ndeclare module '@bemedev/app' {\n  interface Register {\n    'actions': {\n      paths: {\n        map: { targets: ('/idle'); \n        initial: 'idle';\n        states: {\n          'idle': { targets: ('/'); \n          };\n        };\n      };\n        all: '/' | '/idle';\n      };\n      events: never;\n      options: {\n        children: never;\n        emitters: never;\n        tags:     never;\n        actions:  never;\n        delays:   never;\n        guards:   never;\n      };\n      pContext: any;\n    };\n\n    'watch': {\n      paths: {\n        map: { targets: ('/idle'); \n        initial: 'idle';\n        states: {\n          'idle': { targets: ('/'); \n          };\n        };\n      };\n        all: '/' | '/idle';\n      };\n      events: never;\n      options: {\n        children: never;\n        emitters: never;\n        tags:     never;\n        actions:  never;\n        delays:   never;\n        guards:   never;\n      };\n      pContext: any;\n    };\n\n  }\n}\n\nexport {};".trim();

const OUPUT1 = [
  '/**',
  ' * This file is auto-generated by the @bemedev/app CLI.',
  ' * Do not edit manually. Re-run `app generate` or restart `app watch`.',
  ' *',
  ' */',
  '',
  "declare module '@bemedev/app' {",
  '  interface Register {',
  `    'actions': {
      paths: {
        map: { targets: ('/idle'); 
        initial: 'idle';
        states: {
          'idle': { targets: ('/'); 
          };
        };
      };
        all: '/' | '/idle';
      };
      events: never;
      options: {
        children: never;
        emitters: never;
        tags:     never;
        actions:  never;
        delays:   never;
        guards:   never;
      };
      pContext: any;
    };`,
  '',
  '  }',
  '}',
  '',
  `export {};`,
];

const ACTION_FSM_CONTENT = `import { createMachine } from '${LIB}';
import { typings } from '#utils/typings';

export default createMachine(
  'actions',
  {
    initial: 'idle',
    states: { idle: {} },
  },
  {
    pContext: typings.pContext({
      count: 'number',
    }),
  },
);
`;

describe('CLI', () => {
  let watcher: Watcher;
  const CREATED_FILE = './src/__tests__/watch.machine.ts';
  const DIR = dirname(CREATED_FILE);
  const fsmPath = `${DIR}/actions.fsm.ts`;

  it('#00 => ', async () => {
    mkdirSync(DIR, { recursive: true });
    writeFileSync(fsmPath, ACTION_FSM_CONTENT);
    await sleep(500);
  });

  it('#00 => create watcher', async () => {
    watcher = await run(watch, ['-c', DIR]);
    console.warn('watcher started');
  });

  it('#01 => create file', async () => {
    return sleep(500).then(() => {
      writeFileSync(CREATED_FILE, '', {});
      console.warn('writing');
    });
  });

  it('#02 => close watcher', async () => {
    return sleep(500).then(() => {
      watcher.close();
      console.warn('watcher closed');
    });
  });

  it('#03 => check file content', async () => {
    const received = readFileSync(CREATED_FILE, 'utf-8').trim();

    const expected = `
import { createMachine } from '${LIB}';

export default createMachine('watch', { initial: 'idle', states: { idle: {} } })
          `.trim();

    expect(received).toBe(expected);
    console.warn('file content checked');
  });

  it('#04 => delete file', async () => {
    return sleep(100).then(() => {
      unlinkSync(CREATED_FILE);
      console.warn('file deleted');
    });
  });

  it('#05 => check generated file', async () => {
    const generated = readFileSync(`${DIR}/app.gen.ts`, 'utf-8').trim();
    expect(generated).toBe(OUPUT);
    console.warn('generated file checked');
  });

  it('#06 => cli generate', async () => {
    const result = await run(generate, ['-c', DIR, '--dry-run']);

    expect(result).toEqual(OUPUT1);
  });

  it('#07 => delete the only machine left', () => {
    return sleep(100).then(() => {
      const exists = existsSync(`${DIR}/app.gen.ts`);
      expect(exists).toBe(true);
      unlinkSync(`${DIR}/actions.fsm.ts`);
      console.warn('All machine files are deleted');
    });
  });

  it('#08 => cli generate', () => {
    return run(generate, ['-c', DIR, '--dry-run']);
  });

  it('#09 => check generated file is removed', () => {
    const exists = existsSync(`${DIR}/app.gen.ts`);
    expect(exists).toBe(false);
    console.warn('generated file is removed');
  });

  it('#10 => cli generate', () => {
    return run(generate, ['-c', DIR, '--dry-run']);
  });

  it('#11 => No files inside __tests__', () => {
    const files = readdirSync(DIR);
    expect(files.length).toBe(0);
  });

  it('#12 => unlink the dir', () => {
    rmdirSync(DIR);
    console.warn('__tests__ dir is deleted');
    console.warn('');
    console.warn('');
  });
});
