/**
 * This file is auto-generated by the @bemedev/app CLI.
 * Do not edit manually. Re-run `app generate` or restart `app watch`.
 *
 */

declare module '@bemedev/app' {
  interface Register {
    'src/__tests__/actions/action.batch.cov.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial: 'idle';
          states: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'INC1' | 'INC2' | 'INC5';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'inc1' | 'inc2' | 'inc5';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.1.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial: 'idle';
          states: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'loadUser';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.2.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial: 'idle';
          states: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'loadUser';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.3.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial: 'idle';
          states: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'loadUser';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.4.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial: 'idle';
          states: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'PING';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'ping';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/interpreters/common.machine': {
      paths: {
        map: {
          targets:
            | '/idle'
            | '/active'
            | '/active/speed_low'
            | '/active/speed_high'
            | '/final';
          initial: 'idle';
          states: {
            active: {
              targets:
                | '/'
                | '/idle'
                | '/active/speed_low'
                | '/active/speed_high'
                | '/final';
              initial: 'speed_low';
              states: {
                speed_high: {
                  targets:
                    | '/'
                    | '/idle'
                    | '/active'
                    | '/active/speed_low'
                    | '/final';
                };
                speed_low: {
                  targets:
                    | '/'
                    | '/idle'
                    | '/active'
                    | '/active/speed_high'
                    | '/final';
                };
              };
            };
            final: {
              targets:
                | '/'
                | '/idle'
                | '/active'
                | '/active/speed_low'
                | '/active/speed_high';
            };
            idle: {
              targets:
                | '/'
                | '/active'
                | '/active/speed_low'
                | '/active/speed_high'
                | '/final';
            };
          };
        };
        all:
          | '/'
          | '/idle'
          | '/active'
          | '/active/speed_low'
          | '/active/speed_high'
          | '/final';
      };
      events: 'START' | 'INC' | 'ACCELERATE' | 'STOP' | 'DECELERATE';
      options: {
        children: never;
        emitters: never;
        tags: 'idle_tag' | 'active_tag' | 'low_tag' | 'high_tag';
        actions: 'increment';
        delays: never;
        guards: never;
      };
      pContext: any;
    };
  }
}

export {};
