/**
 * This file is auto-generated by the @bemedev/app CLI.
 * Do not edit manually. Re-run `app generate` or restart `app watch`.
 *
 */

declare module '@bemedev/app' {
  interface Register {
    'src/__tests__/actions/action.batch.cov.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial?: 'idle';
          states?: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'INC1' | 'INC2' | 'INC5';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'inc1' | 'inc2' | 'inc5';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/actions.1.machine': {
      paths: {
        map: {
          targets: '/state1' | '/state2';
          initial?: 'state1';
          states?: {
            state1: { targets: '/' | '/state2' };
            state2: { targets: '/' | '/state1' };
          };
        };
        all: '/' | '/state1' | '/state2';
      };
      events: 'NEXT';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'action1';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/actions.2.machine': {
      paths: {
        map: {
          targets: '/state1' | '/state2';
          initial?: 'state1';
          states?: {
            state1: { targets: '/' | '/state2' };
            state2: { targets: '/' | '/state1' };
          };
        };
        all: '/' | '/state1' | '/state2';
      };
      events: 'NEXT';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'action1';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.1.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial?: 'idle';
          states?: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'loadUser';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.2.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial?: 'idle';
          states?: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'loadUser';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.3.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial?: 'idle';
          states?: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'LOAD';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'loadUser';
        delays: never;
        guards: never;
      };
      pContext: any;
    };

    'src/__tests__/actions/async-actions.4.machine': {
      paths: {
        map: {
          targets: '/idle';
          initial?: 'idle';
          states?: {
            idle: { targets: '/' };
          };
        };
        all: '/' | '/idle';
      };
      events: 'PING';
      options: {
        children: never;
        emitters: never;
        tags: never;
        actions: 'ping';
        delays: never;
        guards: never;
      };
      pContext: any;
    };
  }
}

export {};
